eventio/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import login, logout

from accounts.views import register_user
from events.views import index, event_detail, event_add

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='home'),
    url(r'^event/(?P<pk>\d+)/$', event_detail, name='event'),
    url(r'^event/add/$', event_add, name='event_add'),
    url(r'^login/$', login,
    {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^sign-up/$', register_user, name='signup'),
]

accounts/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models

class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_time = models.DateTimeField()
    location = models.CharField(max_length=255)
    price = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=6)
    capacity = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

events/forms.py
from django import forms

from .models import Event


class AddEventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ('name', 'description', 'start_time', 'location', 'price', 'capacity')


        

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        # Create a user
        if form.is_valid():
            #Save the user to the database
            user = form.save()
            # Log in the user
            login(request, user)
            return redirect('/')
    else:
        # Render an empty form
        form = UserCreationForm()
    return render(request,
        'accounts/register.html', {'user_create_form': form})

events/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import AddEventForm
from events.models import Event

# Create your views here.
def index(request):
    events = Event.objects.all()
    return render(request, 'index.html', {'events': events})


def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    return render(request, 'event_detail.html', {'event':event})

def event_add(request):
    if request.method == 'POST':
        form = AddEventForm(request.POST)
        if form.is_valid():
            event = form.save()
            return redirect('event', pk=event.pk)
    else:
        form = AddEventForm()
    return render(request, 'event_add.html', {'form': form})

templates/_partials/base.html
<!doctype html>{% load staticfiles %}
<head>
  <meta charset="utf-8">
  <title>Eventio</title>

  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  {% block head %}{% endblock %}
</head>
<body>
  <nav>
  <div class="container">
    <a class="title" href="/">Eventio</a>

    <div class="menu">
      <a href="/">Home</a>
      <a href="{% url 'event_add' %}">Add Event</a>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Sign Out</a>
      {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'signup' %}">Sign Up</a>


      {% endif %}
    </div>
  </div>
</nav>
  <div class="container">
{% block content %}{% endblock %}
  </div>
{% block scripts %}{% endblock %}
</body>

templates/accounts/login.html
{% extends '_partials/base.html'%}

{% block content %}
  <h1>Login</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log In</button>
  </form>

{% endblock content %}

templates/accounts/register.html
{% extends '_partials/base.html' %}

{% block content %}
<h1>Sign Up</h1>

<form method="post">
  {% csrf_token %}
  {{ user_create_form.as_p }}
  <button type="submit">Sign Up</button>
</form>
{% endblock %}

templates/event_add.html
{% extends '_partials/base.html' %}

{% block head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/2.0.5/flatpickr.airbnb.min.css" />
{% endblock head %}

{% block content %}
  <h1>Add New Event</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <button type="submit">Add Event</button>
  </form>
{% endblock content %}

{% block scripts %}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/2.0.5/flatpickr.min.js"></script>
  <script>
    flatpickr(
      '#id_start_time',
      { minDate: 'today', enableTime: true, }
    );
</script>
{% endblock %}

templates/event_detail.html
{% extends '_partials/base.html' %}

{% block content %}

  <div class="event">
  <h3>{{ event.name }}</h3>
      {% if event.capacity %}
      <p/>
        <strong/><em>Capacity:{{event.capacity}}<em/><strong/></p>
      <p/>
          {% endif %}
      <p>{{event.description}}</p>
      <dl>
        <dt>When:</dt>
        <dd>{{ event.start_time }}</dd>
        <dt>Where:</dt>
        <dd>{{ event.location }}</dd>
        <dt>Price:</dt>
        <dd>
          {% if event.price %}
            ${{ event.price }}
          {% else %}
            FREE
          {% endif %}
        </dd>
      </dl>
    </div>

{% endblock content %}

templates/index.html
{% extends '_partials/base.html' %}

{% block content %}

    <h2>Events List</h2>

    {% for event in events %}
  <div class= "event">
  <h3><a href="{% url 'event' pk=event.pk %}">{{ event.name }}</a></h3>
  <p><em>{{ event.start_time }} at {{ event.location }}</em></p>
    <p>{{ event.description|truncatewords:15 }}</p>
    </div>
{% endfor %}

{% endblock content %}